# This plugin was developed by FN_FAL113 for BarangayCraft Skyblock as an Island Fly Checker.

# You can disable the checker if both settings is commented out.
# Add "#" before permission1: to remove or comment out a setting.
permission1: "cmi.command.fly"
permission2: "bskyblock.island.fly"